# Generated by Django 5.0.4 on 2024-04-28 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication_', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='firstlogin',
            field=models.BooleanField(default=True),
        ),
    ]
