# Generated by Django 5.0.4 on 2024-04-28 18:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication_', '0002_userprofile_firstlogin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='')),
                ('name', models.CharField(default='Wayne Enterprises', max_length=200)),
                ('description', models.TextField(default="Wayne Enterprises is one of the largest conglomerates in world history with operations in aerospace, technology, biotech, shipping, shipbuilding, foods, medicine, electronics, entertainment, alternative energy, steel, chemicals, and philanthropy.\n\nThe colossal organization was founded by Solomon Wayne in the late 17th century, who turned a modest real estate fortune left by his father Charles' estate, into a merchant house. Leveraging his earned status as a prominent Gotham citizen, he grew the company rapidly in the late 1850s and his son Alan Wayne led the breakthrough, incorporating Gotham Railroads, Wayne Shipping, Wayne Chemicals, and Wayne Manufacturing, laying the cement for the diverse powerhouse Wayne Enterprises is today. Alan Wayne's grandson Patrick Morgan Wayne developed WayneTech, one of the most important divisions of the Enterprises, out of the ashes of the Great Depression, whose aircraft and naval technologies fueled the American efforts in the Pacific theater of World War II. \nMr. Patrick Wayne's son, Dr. Thomas Wayne, turned the direction of the company to its current prominence in social responsibility, starting the charitable Wayne Foundation. Following Dr. Wayne's shocking murder, the company's board of directors took the ailing company public in a controversial decision. \n\nToday, Wayne Enterprises is led by Lucius Fox, appointed by playboy billionaire heir Bruce Wayne, whose estate owns a majority stake through various trusts and charities. In 2012, Wayne Enterprises was targeted by an underground guerilla group that defrauded Wayne Enterprises' stock price through deliberate market manipulation. Mr. Wayne went missing following the Gotham nuclear scare but rumors speculate he's alive in Italy and bound to return to his post.")),
                ('registration', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='authentication_.company'),
        ),
    ]
