# Generated by Django 5.0.4 on 2024-04-28 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication_', '0003_company_userprofile_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='resume_json',
            field=models.TextField(default={}),
        ),
    ]
